/* Stage-A flowc frontend ABI for the tiny C host driver.
 *
 * Struct layouts and prototypes come from headers generated by
 * `compiler/scripts/flowc_c_to_hdr.py` out of Stage-A-emitted modules.
 * Compile the driver with `-I compiler/build` after roundtrip has produced
 * those headers (and `compiler/build/flowc_frontend.o`).
 *
 * Include order matters: Parser embeds Lexer/Token/AstArena.
 */
#ifndef FLOWC_FRONTEND_H
#define FLOWC_FRONTEND_H

#include "token_flowc.h"
#include "ast_flowc.h"
#include "lexer_flowc.h"
#include "parser_flowc.h"
#include "cgen_flowc.h"
/* typecheck.flow resolves calls through the native overload modules, so its
   header names their types. Include order matters here: each of these names
   types declared by the one above it. */
#include "overload_flowc.h"
#include "overload_table_flowc.h"
#include "type_name_flowc.h"
#include "expr_type_flowc.h"
#include "overload_args_flowc.h"
#include "overload_select_flowc.h"
#include "overload_registry_flowc.h"
#include "overload_call_flowc.h"
#include "typecheck_flowc.h"
#include "resolve_flowc.h"

#endif /* FLOWC_FRONTEND_H */
